# render.yaml
# Blueprint for deploying the Blox Battles full-stack application on Render.
# This file should be placed in the root directory of your GitHub repository.

databases: # Define the database first
  - name: blox-battles-db # The name for your PostgreSQL database
    databaseName: blox_battles # The actual name of the database inside PostgreSQL
    user: blox_battles_user # The user for the database
    plan: basic-256mb # Use the free tier for PostgreSQL

services:
  # ------------------
  # Backend Web Service (Node.js)
  # ------------------
  - type: web
    name: blox-battles-api # The name of your backend service
    runtime: node
    region: oregon # Or your preferred region
    plan: starter # 'starter' is free, upgrade as needed
    
    # --- Build & Start Configuration ---
    repo: https://github.com/GambleD0re/Blox_Battles.git
    branch: main
    rootDir: ./backend
    # [MODIFIED] Added 'npm install pg' to the build command
    buildCommand: npm install && npm install pg
    startCommand: node server.js

    # --- Health Check ---
    healthCheckPath: /api/health

    # --- Environment Variables ---
    # The DATABASE_URL is automatically injected by Render from the database service above.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db # Must match the database name above
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false # Set in dashboard
      - key: BOT_API_KEY
        sync: false # Set in dashboard

  # ------------------
  # Frontend Static Site (React)
  # ------------------
  - type: static
    name: blox-battles-client
    
    # --- Build & Deploy Configuration ---
    repo: https://github.com/GambleD0re/Blox_Battles.git
    branch: main
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    publishDir: ./dist

    # --- SPA Rewrite Rule ---
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    # --- Environment Variables ---
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: blox-battles-api
          envVarKey: URL
